<?php

namespace Blog\GeneralBundle\Repository;


use Doctrine\ORM\EntityRepository;
/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{

    /**
     * @return \Doctrine\ORM\Query
     */
    public function getAllArticle()
    {
        $qb = $this->createQueryBuilder('a')->getQuery();
        return $qb;
    }

    /**
     * @return \Doctrine\ORM\Query
     */
    public function getAllArticleDateCreateDesc()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.dateCreate', 'DESC');
        return $qb->getQuery();
    }
}
