<?php

namespace Blog\GeneralBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityRepository;
/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{

    public function getArticlesxxxxxxxxxxxxxxxxxx($page, $nbPerPage)
    {
        $query = $this->createQueryBuilder('a')
            ->orderBy('a.dateCreate', 'DESC')
            ->getQuery()
        ;

        $query
            // On définit l'article à partir de laquelle commencer la liste
            ->setFirstResult(($page-1) * $nbPerPage)
            // Ainsi que le nombre d'article à afficher sur une page
            ->setMaxResults($nbPerPage)
        ;

        // Enfin, on retourne l'objet Paginator correspondant à la requête construite
        return new Paginator($query, true);
    }
}
