<?php

namespace Blog\GeneralBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCommentNoPublished()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.published = false')
            ->orderBy('a.dateCreate', 'ASC')
        ;
        return $qb->getQuery()->getResult();
    }

    public function searchcomment($critere)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.title LIKE :title')
           ->setParameter('title','%'.$critere.'%')
           ->orWhere('a.content LIKE :content')
           ->setParameter('content','%'.$critere.'%')
           ->orWhere('a.author LIKE :author')
           ->setParameter('author','%'.$critere.'%');
        return $qb->getQuery()->getResult();

    }

}
