<?php

namespace Blog\GeneralBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Blog\GeneralBundle\Entity\Article;

class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllComment()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.dateCreate', 'DESC');
        return $qb->getQuery();
    }

    /**
     * @return array
     */
    public function getCommentNoPublished()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.published = false')
            ->orderBy('a.dateCreate', 'ASC')
        ;
        return $qb->getQuery()->getResult();
    }

    /**
     * @param Article $article
     * @return array
     */
    public function getCommentLevelOne(Article $article)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.depth = 0')
            ->andWhere('a.article = :article')
            ->setParameter('article', $article)
        ;
        return $qb->getQuery()->getResult();
    }
}
