<?php

namespace Blog\GeneralBundle\Repository;

/**
 * ReportAbusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportAbusRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNewReport()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.newReport = true')
            ->orderBy('a.date', 'ASC')
        ;
        return $qb->getQuery()->getResult();
    }

    public function getAllReportsDateDesc()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.date', 'DESC');
        return $qb->getQuery();
    }
}
