services:
#    blog_general.example:
#        class: Blog\GeneralBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    blog_general.toolsbox:
        class: Blog\GeneralBundle\ToolsBox\ToolsBox
        arguments:
            - "@doctrine.orm.entity_manager"
